import axios from "axios";
import { TranslationResult } from "../models/TranslationResult.js";
import dotenv from "dotenv";

// Load environment variables
dotenv.config();

/**
 * Client for interacting with the LLM service for translations
 */
export class TranslationClient {
  private apiUrl: string;

  constructor() {
    this.apiUrl = process.env.LLM_SERVICE_URL || "http://localhost:1000/api/llm";
  }

  /**
   * Translates a transcript to the target language
   * @param videoId The ID of the video associated with the transcript
   * @param transcript The transcript text to translate
   * @param targetLanguage The language to translate to
   * @returns The translated text
   */
  async translateTranscript(videoId: string, transcript: string, targetLanguage: string): Promise<string> {
    try {
      const response = await axios.post(
        `${this.apiUrl}/translate`,
        {
          videoId,
          text: transcript,
          targetLanguage,
        },
        {
          headers: {
            "Content-Type": "application/json",
          },
        }
      );

      if (response.status !== 200) {
        throw new Error(`Translation service returned status code ${response.status}`);
      }

      return response.data.translatedText;
    } catch (error) {
      console.error("Error in TranslationClient.translateTranscript:", error);
      throw new Error(`Failed to translate transcript: ${(error as Error).message}`);
    }
  }

  /**
   * Saves a translation to the video-db service
   * @param videoId The ID of the video
   * @param language The language of the translation
   * @param translatedText The translated text
   * @returns The saved translation data
   * @deprecated Use the translateTranscript method which now handles saving via the LLM service
   */
  async saveTranslation(
    videoId: string,
    language: string,
    translatedText: string
  ): Promise<TranslationResult> {
    console.warn("saveTranslation is deprecated. The LLM service now handles saving translations.");
    try {
      // Create a TranslationResult object with the data we have
      // This is a temporary solution until this method is removed
      const result: TranslationResult = {
        id: "", // This will be generated by the database
        videoId,
        language,
        translatedText,
        createdAt: new Date().toISOString(),
      };

      return result;
    } catch (error) {
      console.error("Error in TranslationClient.saveTranslation:", error);
      throw new Error(`Failed to save translation: ${(error as Error).message}`);
    }
  }
}
